#!/usr/bin/env python3
"""Generate common/web/css/dragon-lite.css from common/web/css/dragon.css.

The generator keeps root/element rules and CSS selectors whose classes are
referenced by the backend/frontend/common application sources, plus safelisted
runtime classes generated by widgets such as Select2. It intentionally
ignores vendored dependencies, generated assets, runtime files, and the CSS
source directory.
"""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
SOURCE_CSS = ROOT / 'common/web/css/dragon.css'
TARGET_CSS = ROOT / 'common/web/css/dragon-lite.css'
APP_DIRS = ('frontend', 'backend', 'common')
TEXT_EXTENSIONS = {'.php', '.js', '.html', '.htm', '.twig', '.vue', '.txt', '.md', '.json'}
CLASS_RE = re.compile(r'\.(-?[_a-zA-Z][\w-]*)')
NOT_PSEUDO_RE = re.compile(r':not\((?:[^()]|\([^()]*\))*\)')
WORD_RE = re.compile(r'[A-Za-z_][A-Za-z0-9_-]*|-[_A-Za-z][A-Za-z0-9_-]*')
RUNTIME_CLASS_PREFIXES = ('select2-',)
RUNTIME_CLASSES = {'select2-container', 'select2-dropdown'}


def app_source_files() -> list[Path]:
    files = subprocess.check_output([
        'rg', '--files', *APP_DIRS,
        '-g', '!**/node_modules/**',
        '-g', '!vendor/**',
        '-g', '!**/runtime/**',
        '-g', '!**/web/assets/**',
        '-g', '!common/web/css/**',
        '-g', '!frontend/web/offline/**',
    ], cwd=ROOT, text=True).splitlines()

    return [ROOT / file for file in files if Path(file).suffix.lower() in TEXT_EXTENSIONS]


def used_words() -> set[str]:
    words: set[str] = set()
    for path in app_source_files():
        words.update(WORD_RE.findall(path.read_text(errors='ignore')))

    return words


def matching_brace(source: str, open_index: int) -> int:
    depth = 0
    quote = None
    escaped = False
    comment = False

    for index in range(open_index, len(source)):
        char = source[index]
        next_char = source[index + 1] if index + 1 < len(source) else ''

        if comment:
            if char == '*' and next_char == '/':
                comment = False
        elif quote:
            if escaped:
                escaped = False
            elif char == '\\':
                escaped = True
            elif char == quote:
                quote = None
        else:
            if char == '/' and next_char == '*':
                comment = True
            elif char in ('"', "'"):
                quote = char
            elif char == '{':
                depth += 1
            elif char == '}':
                depth -= 1
                if depth == 0:
                    return index

    raise ValueError('Unmatched CSS brace')


def required_selector_classes(selector: str) -> list[str]:
    """Return classes that must be source-referenced for a selector to be kept.

    Classes inside :not(...) are intentionally ignored because they describe
    exclusions on an otherwise-used selector. Runtime classes generated by
    third-party widgets are handled by the runtime safelist.
    """
    selector_without_not = NOT_PSEUDO_RE.sub('', selector)

    return CLASS_RE.findall(selector_without_not)


def runtime_classes(source_classes: set[str]) -> set[str]:
    return {
        css_class for css_class in source_classes
        if css_class in RUNTIME_CLASSES
        or any(css_class.startswith(prefix) for prefix in RUNTIME_CLASS_PREFIXES)
    }


def split_selectors(selector_text: str) -> list[str]:
    selectors = []
    start = 0
    depth = 0
    quote = None
    escaped = False

    for index, char in enumerate(selector_text):
        if quote:
            if escaped:
                escaped = False
            elif char == '\\':
                escaped = True
            elif char == quote:
                quote = None
        else:
            if char in ('"', "'"):
                quote = char
            elif char in '([':
                depth += 1
            elif char in ')]':
                depth = max(0, depth - 1)
            elif char == ',' and depth == 0:
                selectors.append(selector_text[start:index].strip())
                start = index + 1

    tail = selector_text[start:].strip()
    if tail:
        selectors.append(tail)

    return selectors


def format_declarations(body: str, level: int) -> str:
    indent = '    ' * level
    return '\n'.join(f'{indent}{line.strip()}' for line in body.strip().splitlines() if line.strip())


def merge_rule(rules: OrderedDict[str, str], selector: str, body: str, level: int) -> None:
    formatted_body = format_declarations(body, level + 1)
    key = f'{level}:{selector}'

    if key in rules:
        rules[key] = f'{rules[key]}\n{formatted_body}'
        return

    indent = '    ' * level
    rules[key] = f'{indent}{selector} {{\n{formatted_body}\n{indent}}}'


def purge_block(source: str, used_classes: set[str], level: int = 0) -> str:
    rules: OrderedDict[str, str] = OrderedDict()
    position = 0

    while True:
        open_index = source.find('{', position)
        if open_index < 0:
            break

        selector_text = source[position:open_index].strip()
        close_index = matching_brace(source, open_index)
        body = source[open_index + 1:close_index]
        position = close_index + 1

        if not selector_text:
            continue

        if selector_text.startswith('@'):
            if '{' in body:
                inner = purge_block(body, used_classes, level + 1).strip()
                if inner:
                    indent = '    ' * level
                    rules[f'{level}:{selector_text}:{open_index}'] = f'{indent}{selector_text} {{\n{inner}\n{indent}}}'
            elif not CLASS_RE.findall(f'{selector_text} {body}'):
                indent = '    ' * level
                declarations = format_declarations(body, level + 1)
                rules[f'{level}:{selector_text}:{open_index}'] = f'{indent}{selector_text} {{\n{declarations}\n{indent}}}'
            continue

        kept_selectors = []
        for selector in split_selectors(selector_text):
            selector_classes = required_selector_classes(selector)
            if not selector_classes or all(css_class in used_classes for css_class in selector_classes):
                kept_selectors.append(selector)

        if kept_selectors:
            merge_rule(rules, (',\n' + '    ' * level).join(kept_selectors), body, level)

    return '\n\n'.join(rules.values())


def main() -> None:
    source = SOURCE_CSS.read_text()
    all_classes = set(CLASS_RE.findall(source))
    used_classes = (all_classes & used_words()) | runtime_classes(all_classes)
    header = '''/* Generated from dragon.css by retaining selectors used by the frontend and backend applications.
   Source: common/web/css/dragon.css
   Regenerate with: python tools/generate_dragon_lite.py */

'''
    TARGET_CSS.write_text(f'{header}{purge_block(source, used_classes).rstrip()}\n')
    print(f'Generated {TARGET_CSS.relative_to(ROOT)} with {len(used_classes)} used classes out of {len(all_classes)} source classes.')


if __name__ == '__main__':
    main()
